const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),readline=require('readline');
const root=path.resolve(__dirname,'../..'),outDir=path.join(root,'.daily-runtime','tts-output'),reportFile=path.join(root,'daily-agent','test-output','kokoro-tts.json');
fs.mkdirSync(outDir,{recursive:true});const worker=spawn(process.execPath,[path.join(__dirname,'kokoro-tts.cjs'),'--worker'],{cwd:root,windowsHide:true,stdio:['pipe','pipe','pipe']});
const pending=new Map(),report={started:new Date().toISOString(),gpu:false,voice:'zf_001'},errors=[];worker.stderr.on('data',x=>errors.push(String(x)));
const lines=readline.createInterface({input:worker.stdout});let readyResolve;const ready=new Promise(r=>readyResolve=r);
lines.on('line',line=>{const m=JSON.parse(line);if(m.ready)readyResolve();else pending.get(m.id)?.(m);});
function request(id,text,file,speed){return new Promise(resolve=>{pending.set(id,resolve);worker.stdin.write(JSON.stringify({id,text,sid:3,speed,output:file})+'\n');});}
(async()=>{try{const start=Date.now();await Promise.race([ready,new Promise((_,r)=>setTimeout(()=>r(Error('warm timeout')),30000))]);report.warmMs=Date.now()-start;report.workerPid=worker.pid;report.workerRamMiB=Math.round(processInfo(worker.pid)/1048576);
  for(let i=1;i<=2;i++){const file=path.join(outDir,i===2?'kokoro-zf001-preview.wav':`smoke-${i}.wav`),at=Date.now(),speed=i===1?.8:1.3,result=await request(String(i),'你在看什麼呀。讓我也看看。',file,speed);if(!result.ok)throw Error(result.error);const data=fs.readFileSync(file);if(data.subarray(0,4).toString()!=='RIFF')throw Error('invalid wav');report[`generation${i}Ms`]=Date.now()-at;report[`audio${i}Seconds`]=Math.round(result.samples/result.sampleRate*100)/100;report[`speed${i}`]=speed;if(i===1)fs.unlinkSync(file);}if(report.audio1Seconds<=report.audio2Seconds)throw Error('speech speed did not shorten audio');
  report.passed=true;
}catch(e){report.error=e.stack;process.exitCode=1;}finally{worker.stdin.end();worker.kill();worker.stdout.destroy();worker.stderr.destroy();worker.unref();lines.close();delete report.workerPid;report.diagnostics=errors.join('').trim().slice(0,300);fs.mkdirSync(path.dirname(reportFile),{recursive:true});fs.writeFileSync(reportFile,JSON.stringify(report,null,2));const code=process.exitCode||0;process.stdout.write(JSON.stringify(report)+'\n',()=>process.exit(code));}})();
function processInfo(pid){try{return Number(require('child_process').execFileSync('powershell.exe',['-NoProfile','-Command',`(Get-Process -Id ${pid}).WorkingSet64`],{windowsHide:true}).toString().trim())||0;}catch{return 0;}}
